In [1]:
import numpy as np

In [2]:
with open('input.txt') as f:
    binary = tuple(line.strip() for line in f)

In [3]:
outputs = []
for number in binary:
    outputs.append([int(bit) for bit in number])
bits = np.array(outputs)

In [4]:
bits

array([[1, 1, 0, ..., 1, 0, 0],
       [0, 1, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 1, 0],
       ...,
       [0, 1, 0, ..., 0, 1, 1],
       [1, 1, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 0, 1, 0]])

In [5]:
most_common_bit = np.round(np.mean(bits, axis=0))
least_common_bit = 1 - most_common_bit

In [6]:
least_common_bit = 1 - most_common_bit

In [7]:
most_common_bit

array([0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0.])

In [8]:
powers_of_2 = np.flip([2**i for i in range(len(most_common_bit))])

In [9]:
gamma = int(np.sum(powers_of_2*most_common_bit))
epsilon = int(np.sum(powers_of_2*least_common_bit))

In [10]:
gamma*epsilon

2640986

In [11]:
def convert_bit_array_to_int(bits):
    powers_of_2 = np.flip([2**i for i in range(len(bits))])
    number = int(np.sum(powers_of_2 * bits))
    return number

In [12]:
convert_bit_array_to_int(most_common_bit)

802

In [13]:
most_common_bit

array([0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0.])

In [14]:
matching_bits = bits == most_common_bit
matching_bits

array([[False, False, False, ..., False, False,  True],
       [ True, False, False, ..., False, False,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True, False, False, ...,  True,  True, False],
       [False, False, False, ...,  True, False, False],
       [False,  True, False, ...,  True,  True,  True]])

In [15]:
oxygen_matches = bits[np.argmin(matching_bits, axis=1) == np.max(np.argmin(matching_bits, axis=1))]
oxygen_matches

array([[0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1],
       [0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1]])

In [16]:
oxygen_matches ==  most_common_bit

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True, False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False, False, False]])

In [17]:
oxygen_bits = bits[np.argmax(np.argmin(matching_bits, axis=1))]
oxygen_rating = convert_bit_array_to_int(oxygen_bits)
oxygen_rating

807

In [18]:
matching_bits = bits == least_common_bit
scrubber_bits = bits[np.argmax(np.argmin(matching_bits, axis=1))]
scrubber_rating = convert_bit_array_to_int(scrubber_bits)
scrubber_rating

3291

In [19]:
scrubber_matches = bits[np.argmin(matching_bits, axis=1) == np.max(np.argmin(matching_bits, axis=1))]
scrubber_matches


array([[1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1],
       [1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1]])

In [20]:
matching_bits = bits == least_common_bit
bits[np.argmin(matching_bits, axis=1) == 9]


array([[1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1],
       [1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1]])

In [21]:
convert_bit_array_to_int([1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1])

3291

In [22]:
3291*809

2662419

In [23]:
potential_matches = bits

i = 0
while len(potential_matches) > 1:
    if np.any(potential_matches[:, i] == most_common_bit[i]):
        potential_matches = potential_matches[potential_matches[:, i] == most_common_bit[i]]
    i += 1
potential_matches

array([[0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1]])

In [24]:
convert_bit_array_to_int([0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1])

807

In [39]:
potential_matches = bits

i = 0
while len(potential_matches) > 1:
    mean_bit = np.mean(potential_matches, axis=0)
    most_common_bit = np.where(mean_bit == 0.5, 1, np.round(mean_bit))
    if np.any(potential_matches[:, i] == most_common_bit[i]):
        potential_matches = potential_matches[potential_matches[:, i] == most_common_bit[i]]
    i += 1
potential_matches

array([[0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1]])

In [40]:
convert_bit_array_to_int([0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1])

1883

In [41]:
potential_matches = bits

i = 0
while len(potential_matches) > 1:
    mean_bit = np.mean(potential_matches, axis=0)
    least_common_bit = 1 - np.where(mean_bit == 0.5, 1, np.round(mean_bit))
    if np.any(potential_matches[:, i] == least_common_bit[i]):
        potential_matches = potential_matches[potential_matches[:, i] == least_common_bit[i]]
    i += 1
potential_matches

array([[1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1]])

In [42]:
convert_bit_array_to_int([1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1])

3623

In [43]:
3623*1883

6822109

In [30]:
int(.5)

0

In [31]:
np.round(0.5, 0)

0.0

In [32]:
np.mean(bits, axis=0)

array([0.486, 0.498, 0.506, 0.507, 0.491, 0.495, 0.525, 0.485, 0.487,
       0.498, 0.516, 0.477])

In [33]:
means = np.mean(bits, axis=0)
means[2] = 0.5
means


array([0.486, 0.498, 0.5  , 0.507, 0.491, 0.495, 0.525, 0.485, 0.487,
       0.498, 0.516, 0.477])

array([0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0.])

In [38]:
potential
mean_bit = np.mean(bits, axis=0)
modal_bit = np.where(mean_bit == 0.5, 1, np.round(means))
