In [1]:
import numpy as np

In [4]:
with open('input.txt') as f:
    binary = tuple(line.strip() for line in f)

In [47]:
outputs = []
for number in binary:
    outputs.append([int(bit) for bit in number])
bits = np.array(outputs)

In [41]:
bits

array([[1, 1, 0, ..., 1, 0, 0],
       [0, 1, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 1, 0],
       ...,
       [0, 1, 0, ..., 0, 1, 1],
       [1, 1, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 0, 1, 0]], dtype=uint8)

In [46]:
most_common_bit = np.round(np.mean(bits, axis=0))
least_common_bit = 1 - most_common_bit

In [43]:
least_common_bit = 1 - most_common_bit

In [135]:
most_common_bit

array([0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0.])

In [53]:
powers_of_2 = np.flip([2**i for i in range(len(most_common_bit))])

In [57]:
gamma = int(np.sum(powers_of_2*most_common_bit))
epsilon = int(np.sum(powers_of_2*least_common_bit))

In [58]:
gamma*epsilon

2640986

In [59]:
def convert_bit_array_to_int(bits):
    powers_of_2 = np.flip([2**i for i in range(len(bits))])
    number = int(np.sum(powers_of_2 * bits))
    return number

In [60]:
convert_bit_array_to_int(most_common_bit)

802

In [71]:
most_common_bit

array([0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0.])

In [97]:
matching_bits = bits == most_common_bit
matching_bits

array([[False, False, False, ..., False, False,  True],
       [ True, False, False, ..., False, False,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True, False, False, ...,  True,  True, False],
       [False, False, False, ...,  True, False, False],
       [False,  True, False, ...,  True,  True,  True]])

In [104]:
oxygen_matches = bits[np.argmin(matching_bits, axis=1) == np.max(np.argmin(matching_bits, axis=1))]
oxygen_matches

array([[0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1],
       [0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1]])

In [105]:
oxygen_matches ==  most_common_bit

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True, False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False, False, False]])

In [89]:
oxygen_bits = bits[np.argmax(np.argmin(matching_bits, axis=1))]
oxygen_rating = convert_bit_array_to_int(oxygen_bits)
oxygen_rating

807

In [106]:
matching_bits = bits == least_common_bit
scrubber_bits = bits[np.argmax(np.argmin(matching_bits, axis=1))]
scrubber_rating = convert_bit_array_to_int(scrubber_bits)
scrubber_rating

3291

In [108]:
scrubber_matches = bits[np.argmin(matching_bits, axis=1) == np.max(np.argmin(matching_bits, axis=1))]
scrubber_matches


array([[1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1],
       [1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1]])

In [95]:
matching_bits = bits == least_common_bit
bits[np.argmin(matching_bits, axis=1) == 9]


array([[1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1],
       [1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1]])

In [111]:
convert_bit_array_to_int([1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1])

3291

In [112]:
3291*809

2662419

In [120]:
potential_matches = bits

i = 0
while len(potential_matches) > 1:
    if np.any(potential_matches[:, i] == most_common_bit[i]):
        potential_matches = potential_matches[potential_matches[:, i] == most_common_bit[i]]
    i += 1
potential_matches

array([[0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1]])

In [121]:
convert_bit_array_to_int([0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1])

807

In [143]:
potential_matches = bits

i = 0
while len(potential_matches) > 1:
    mean_bit = np.mean(bits, axis=0)
    most_common_bit = np.where(mean_bit == 0.5, 1, np.round(mean_bit))
    if np.any(potential_matches[:, i] == most_common_bit[i]):
        potential_matches = potential_matches[potential_matches[:, i] == most_common_bit[i]]
    i += 1
potential_matches

array([[0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1]])

In [144]:
convert_bit_array_to_int([0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1])

807

In [125]:
most_common_bit

array([0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0.])

In [126]:
np.round([0.5, .6, 0.3])

array([0., 1., 0.])

In [134]:
round(.5, )

0.5

In [129]:
int(.5)

0

In [131]:
np.round(0.5, 0)

0.0

In [136]:
np.mean(bits, axis=0)

array([0.486, 0.498, 0.506, 0.507, 0.491, 0.495, 0.525, 0.485, 0.487,
       0.498, 0.516, 0.477])

In [140]:
means = np.mean(bits, axis=0)
means[2] = 0.5
means


array([0.486, 0.498, 0.5  , 0.507, 0.491, 0.495, 0.525, 0.485, 0.487,
       0.498, 0.516, 0.477])

In [141]:
np.where(means == 0.5, 1, np.round(means))

array([0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0.])