In [101]:
import numpy as np
import re

with open('inputs/day06.txt') as f:
    instructions = tuple(line.strip() for line in f)

In [118]:
grid = np.zeros(shape=(1000, 1000))
grid

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [17]:
# Toggle = XOR

grid[range(0, 2), 0:5] = 1

In [107]:
grid

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [25]:
grid[range(0, 2), 0:5]

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [95]:
text = 'toggle 461,550 through 564,900'

matches = [int(match) for match in re.findall(r'(\d{1,3})', text)]

In [103]:
x_start, y_start, x_end, y_end = matches

x_range = range(x_start, x_end+1)
y_range = range(y_start, y_end+1)

In [88]:
re.search(r'toggle|on|off', text).group()

'toggle'

In [98]:
x_start

461

In [100]:
np.logical_not(np.array([1, 0, 1, 0]))

array([False,  True, False,  True])

In [119]:
for instruction in instructions:
    command = re.search(r'toggle|on|off', text).group()
    matches = [int(match) for match in re.findall(r'(\d{1,3})', instruction)]
    x_start, y_start, x_end, y_end = matches

    x_range = range(x_start, x_end+1)
    y_range = range(y_start, y_end+1)

    if command == 'toggle':
        grid[x_start:x_end+1, y_start:y_end+1] = np.logical_not(grid[x_start:x_end+1, y_start:y_end+1])
    elif command == 'on':
        grid[x_start:x_end+1, y_start:y_end+1] = 1
    elif command == 'off':
        grid[x_start:x_end+1, y_start:y_end+1] = 0
    
    

In [120]:
np.sum(grid)

478124.0