In [1]:
import numpy as np
from scipy.signal import convolve2d

with open("inputs/day11_test.txt") as f:
    waiting_area = tuple(line.strip() for line in f)

is_seat = np.array(
    [[1 if space != "." else 0 for space in row] for row in waiting_area]
)

seats_occupied = np.array(
    [[1 if space == "#" else 0 for space in row] for row in waiting_area]
)


c = np.ones(shape=(3, 3), dtype=np.int8)
c[1, 1] = 0

while True:
    previous_state = np.copy(seats_occupied)
    adjacent_seats_occupied = np.uint8(convolve2d(seats_occupied, c, mode="same"))
    seats_becoming_occupied = is_seat & (adjacent_seats_occupied == 0)
    seats_becoming_empty = is_seat & (adjacent_seats_occupied >= 4)
    seats_occupied = np.where(seats_becoming_occupied, 1, seats_occupied)
    seats_occupied = np.where(seats_becoming_empty, 0, seats_occupied)
    if np.all(seats_occupied == previous_state):
        break
        

print(np.sum(seats_occupied))

37


In [2]:
c

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]], dtype=int8)

In [38]:
seats_occupied = np.where(seats_becoming_occupied, 1, seats_occupied)
seats_occupied = np.where(seats_becoming_empty, 0, seats_occupied)
seats_occupied

array([[1, 0, 1, 0, 0, 0, 1, 0, 1, 1],
       [1, 0, 0, 0, 1, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 1, 1, 0, 1, 1, 0, 0, 1],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 1, 0, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 1]])

In [39]:
left = np.cumsum(seats_occupied, axis=1) - seats_occupied
left = np.where(left > 0, 1, 0)
left

array([[0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [40]:
right = np.cumsum(seats_occupied[:, ::-1], axis=1)[:, ::-1] - seats_occupied
right = np.where(right > 0, 1, 0)
right

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 0]])

In [41]:
up = np.cumsum(seats_occupied, axis=0) - seats_occupied
up = np.where(up > 0, 1, 0)
up

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 1, 0, 1, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 1],
       [1, 0, 1, 0, 1, 0, 1, 1, 1, 1],
       [1, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 1, 1, 1, 1, 1, 1, 1]])

In [42]:
down = np.cumsum(seats_occupied[::-1, :], axis=0)[::-1, :] - seats_occupied
down = np.where(down > 0, 1, 0)
down

array([[1, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 0, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 0, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 0, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 0, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [43]:
seats_occupied

array([[1, 0, 1, 0, 0, 0, 1, 0, 1, 1],
       [1, 0, 0, 0, 1, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 1, 1, 0, 1, 1, 0, 0, 1],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 1, 0, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 1]])

In [44]:
num_rows = len(seats_occupied)
num_cols = len(seats_occupied[0])

In [45]:
is_seat

array([[1, 0, 1, 1, 0, 1, 1, 0, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 0, 1, 1],
       [1, 0, 1, 0, 1, 0, 0, 1, 0, 0],
       [1, 1, 1, 1, 0, 1, 1, 0, 1, 1],
       [1, 0, 1, 1, 0, 1, 1, 0, 1, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1, 1],
       [0, 0, 1, 0, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1, 1]])

In [46]:
x = 0
y = 0

down_right = dict()
coord = (x, y)
down_right

{}

In [47]:
seat_coords = tuple((row, col) for row in range(num_rows) for col in range(num_cols) if is_seat[row, col])
down_right = {coord:[] for coord in seat_coords}

for coord in seat_coords:
    x, y = coord
    x += 1
    y += 1
    while x < num_rows and y < num_cols:
        if is_seat[x, y]:
            down_right[coord].append((x, y))
        x += 1
        y += 1

In [48]:
down_right = {k:v for k, v in down_right.items() if v}

In [49]:
up_left = {coord:[] for coord in seat_coords}

for coord in seat_coords:
    x, y = coord
    x -= 1
    y -= 1
    while (0 <= x < num_rows) and (0 <= y < num_cols):
        if is_seat[x, y]:
            up_left[coord].append((x, y))
        x -= 1
        y -= 1
        
up_left = {k:v for k, v in up_left.items() if v}

In [50]:
is_seat

array([[1, 0, 1, 1, 0, 1, 1, 0, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 0, 1, 1],
       [1, 0, 1, 0, 1, 0, 0, 1, 0, 0],
       [1, 1, 1, 1, 0, 1, 1, 0, 1, 1],
       [1, 0, 1, 1, 0, 1, 1, 0, 1, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1, 1],
       [0, 0, 1, 0, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1, 1]])

In [51]:
up_right = {coord:[] for coord in seat_coords}

for coord in seat_coords:
    x, y = coord
    x -= 1
    y += 1
    while (0 <= x < num_rows) and (0 <= y < num_cols):
        if is_seat[x, y]:
            up_right[coord].append((x, y))
        x -= 1
        y += 1
        
up_right = {k:v for k, v in up_right.items() if v}

In [52]:
down_left = {coord:[] for coord in seat_coords}

for coord in seat_coords:
    x, y = coord
    x += 1
    y -= 1
    while (0 <= x < num_rows) and (0 <= y < num_cols):
        if is_seat[x, y]:
            down_left[coord].append((x, y))
        x += 1
        y -= 1
        
down_left = {k:v for k, v in down_left.items() if v}
down_left

{(0, 2): [(1, 1), (2, 0)],
 (0, 3): [(1, 2), (3, 0)],
 (0, 5): [(1, 4), (3, 2), (5, 0)],
 (0, 6): [(1, 5), (2, 4), (3, 3), (4, 2)],
 (0, 8): [(3, 5), (5, 3), (6, 2), (7, 1), (8, 0)],
 (0, 9): [(1, 8), (2, 7), (3, 6), (4, 5), (5, 4), (7, 2), (9, 0)],
 (1, 1): [(2, 0)],
 (1, 2): [(3, 0)],
 (1, 3): [(2, 2), (3, 1), (4, 0)],
 (1, 4): [(3, 2), (5, 0)],
 (1, 5): [(2, 4), (3, 3), (4, 2)],
 (1, 6): [(4, 3), (5, 2), (7, 0)],
 (1, 8): [(2, 7), (3, 6), (4, 5), (5, 4), (7, 2), (9, 0)],
 (1, 9): [(4, 6), (5, 5), (6, 4), (7, 3), (8, 2)],
 (2, 2): [(3, 1), (4, 0)],
 (2, 4): [(3, 3), (4, 2)],
 (2, 7): [(3, 6), (4, 5), (5, 4), (7, 2), (9, 0)],
 (3, 1): [(4, 0)],
 (3, 2): [(5, 0)],
 (3, 3): [(4, 2)],
 (3, 5): [(5, 3), (6, 2), (7, 1), (8, 0)],
 (3, 6): [(4, 5), (5, 4), (7, 2), (9, 0)],
 (3, 8): [(5, 6), (7, 4), (8, 3), (9, 2)],
 (3, 9): [(4, 8), (7, 5), (8, 4), (9, 3)],
 (4, 3): [(5, 2), (7, 0)],
 (4, 5): [(5, 4), (7, 2), (9, 0)],
 (4, 6): [(5, 5), (6, 4), (7, 3), (8, 2)],
 (4, 8): [(7, 5), (8, 4), (9, 3

In [53]:
seats_occupied

array([[1, 0, 1, 0, 0, 0, 1, 0, 1, 1],
       [1, 0, 0, 0, 1, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 1, 1, 0, 1, 1, 0, 0, 1],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 1, 0, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 1]])

In [54]:
directions = (up_left, up_right, down_left, down_right)
coord = (2, 2)

for direction in directions:
    if coord in direction:
        coords_to_check = direction[coord]
        any(seats_occupied[coords2] for coords2 in coords_to_check)

In [55]:
up_right

{(1, 1): [(0, 2)],
 (1, 2): [(0, 3)],
 (1, 4): [(0, 5)],
 (1, 5): [(0, 6)],
 (1, 8): [(0, 9)],
 (2, 0): [(1, 1), (0, 2)],
 (2, 2): [(1, 3)],
 (2, 4): [(1, 5), (0, 6)],
 (2, 7): [(1, 8), (0, 9)],
 (3, 0): [(1, 2), (0, 3)],
 (3, 1): [(2, 2), (1, 3)],
 (3, 2): [(1, 4), (0, 5)],
 (3, 3): [(2, 4), (1, 5), (0, 6)],
 (3, 5): [(0, 8)],
 (3, 6): [(2, 7), (1, 8), (0, 9)],
 (4, 0): [(3, 1), (2, 2), (1, 3)],
 (4, 2): [(3, 3), (2, 4), (1, 5), (0, 6)],
 (4, 3): [(1, 6)],
 (4, 5): [(3, 6), (2, 7), (1, 8), (0, 9)],
 (4, 6): [(1, 9)],
 (4, 8): [(3, 9)],
 (5, 0): [(3, 2), (1, 4), (0, 5)],
 (5, 2): [(4, 3), (1, 6)],
 (5, 3): [(3, 5), (0, 8)],
 (5, 4): [(4, 5), (3, 6), (2, 7), (1, 8), (0, 9)],
 (5, 5): [(4, 6), (1, 9)],
 (5, 6): [(3, 8)],
 (5, 8): [(4, 9)],
 (6, 2): [(5, 3), (3, 5), (0, 8)],
 (6, 4): [(5, 5), (4, 6), (1, 9)],
 (7, 0): [(5, 2), (4, 3), (1, 6)],
 (7, 1): [(6, 2), (5, 3), (3, 5), (0, 8)],
 (7, 2): [(5, 4), (4, 5), (3, 6), (2, 7), (1, 8), (0, 9)],
 (7, 3): [(6, 4), (5, 5), (4, 6), (1, 9)],
 (

In [56]:
num_diagonal_neighbors = np.where(is_seat, 0, 0)
num_diagonal_neighbors

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [57]:
for direction in directions:
    for seat, coords_to_check in direction.items():
        num_diagonal_neighbors[seat] += any(seats_occupied[coord] for coord in coords_to_check)

In [58]:
num_diagonal_neighbors

array([[1, 0, 1, 2, 0, 2, 2, 0, 2, 1],
       [1, 3, 2, 3, 2, 3, 2, 0, 2, 1],
       [2, 0, 3, 0, 4, 0, 0, 2, 0, 0],
       [1, 3, 4, 4, 0, 4, 4, 0, 2, 2],
       [1, 0, 2, 3, 0, 3, 3, 0, 3, 2],
       [2, 0, 3, 4, 4, 3, 1, 0, 2, 1],
       [0, 0, 3, 0, 3, 0, 0, 0, 0, 0],
       [2, 2, 4, 2, 4, 2, 4, 3, 2, 1],
       [1, 0, 1, 4, 2, 4, 2, 3, 0, 2],
       [1, 0, 2, 1, 2, 2, 1, 0, 1, 1]])

In [59]:
with open("inputs/day11.txt") as f:
    waiting_area = tuple(line.strip() for line in f)

is_seat = np.array(
    [[1 if space != "." else 0 for space in row] for row in waiting_area]
)

seats_occupied = np.array(
    [[1 if space == "#" else 0 for space in row] for row in waiting_area]
)


In [60]:
while True:
    previous_state = np.copy(seats_occupied)

    left = np.cumsum(seats_occupied, axis=1) - seats_occupied
    left = np.where(left > 0, 1, 0)
    right = np.cumsum(seats_occupied[:, ::-1], axis=1)[:, ::-1] - seats_occupied
    right = np.where(right > 0, 1, 0)
    up = np.cumsum(seats_occupied, axis=0) - seats_occupied
    up = np.where(up > 0, 1, 0)
    down = np.cumsum(seats_occupied[::-1, :], axis=0)[::-1, :] - seats_occupied
    down = np.where(down > 0, 1, 0)

    num_diagonal_neighbors = np.where(is_seat, 0, 0)
    for direction in directions:
        for seat, coords_to_check in direction.items():
            num_diagonal_neighbors[seat] += any(seats_occupied[coord] for coord in coords_to_check)

    total_neighbors = left + right + up + down + num_diagonal_neighbors
    seats_becoming_occupied = is_seat & (total_neighbors == 0)
    seats_becoming_empty = is_seat & (total_neighbors >= 5)
    seats_occupied = np.where(seats_becoming_occupied, 1, seats_occupied)
    seats_occupied = np.where(seats_becoming_empty, 0, seats_occupied)

    if np.all(seats_occupied == previous_state):
        break
        


In [61]:
np.sum(seats_occupied)

8170